apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: sqldbs.infra.example.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.replicas
    description: The number of replicas launched
    name: Replicas
    type: integer
  - JSONPath: .status.phase
    description: status of the DB
    name: Status
    type: string
  - JSONPath: .status.endpoint
    description: Endpoint to access the DB
    name: Endpoint
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: infra.example.com
  names:
    kind: SqlDB
    plural: sqldbs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of the desired behavior of SqlDB.
          properties:
            backupName:
              description: Name of SqlBackup resource. If specified, it means restoring
                the database instances loaded with backup data.
              type: string
            disk:
              description: Details of underlying disk that stores SQL dumps.
              properties:
                sizeGB:
                  description: Disk size in GB. Default to 1 if not specified.
                  format: int32
                  type: integer
                type:
                  description: Disk type. Currently support only "ZonalPersistentDisk"
                    type for demo purpose. Default to "ZonalPersistentDisk" if not
                    specified.
                  type: string
              type: object
            replicas:
              description: Number of database instances. Default to 1 if not specified.
              format: int32
              type: integer
            type:
              description: Sql database type. Currently only support "PostgreSQL"
                type.
              type: string
            version:
              description: Version of the database (e.g., "1.5.1", "latest"). Default
                to "latest" if not specified.
              type: string
          required:
          - type
          - disk
          type: object
        status:
          description: 'Most recently observed status of SqlDB. This data may be out
            of date by some window of time. Populated by the system. Read-only. More
            info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status'
          properties:
            endpoint:
              description: Endpoint exposes the SQLDB instance.
              type: string
            phase:
              description: Status of deployment of database instances.
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
