apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: sqlbackups.infra.example.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: status of the backup
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: infra.example.com
  names:
    kind: SqlBackup
    plural: sqlbackups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of the desired behavior of SqlBackup.
          properties:
            fileName:
              description: Backup file name. Default to "db.dump" if not specified.
              type: string
            sqlDBName:
              description: Name of SqlDB resource that has its database instances
                performed backup with.
              type: string
          required:
          - sqlDBName
          type: object
        status:
          description: 'Most recently observed status of SqlBackup. This data may
            be out of date by some window of time. Populated by the system. Read-only.
            More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status'
          properties:
            phase:
              description: Backup status.
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
