apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: sqldbs.operator.k8s.io
spec:
  group: operator.k8s.io
  names:
    kind: SqlDB
    plural: sqldbs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backupName:
              description: Name of RelationalBackup resource. If specified, it means
                creating the database instances loaded with backup data.
              type: string
            disk:
              description: Details of underlying disk that stores SQL dumps.
              properties:
                sizeGB:
                  description: Disk size in GB. Default to 10 if not specified.
                  format: int32
                  type: integer
                type:
                  description: Disk type. Currently support only "ZonalPersistentDisk"
                    type for demo purpose. Default to "ZonalPersistentDisk" if not
                    specified.
                  type: string
              type: object
            replicas:
              description: Number of database instances. Default to 1 if not specified.
              format: int32
              type: integer
            type:
              description: Sql database type. Currently support "PostgreSQL" and "MySQL"
                types.
              type: string
            version:
              description: Version of the database (e.g., "1.5.1", "latest"). Default
                to "latest" if not specified.
              type: string
          required:
          - type
          - disk
          type: object
        status:
          properties:
            endpoints:
              description: Endpoints of database instances. The number of endpoints
                should be equal to the number of database instances.
              items:
                type: string
              type: array
            succeeded:
              description: Status of deployment of database instances. True if the
                deployment has completed successfully.
              type: boolean
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
