apiVersion: operator.k8s.io/v1alpha1
kind: SqlDB
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sqldb-sample
spec:
  type: PostgreSQL
  version: latest
  replicas: 1
  disk:
    type: ZonalPersistentDisk
    sizeGB: 1
  # uncomment following field to perform restore
  # backupName: sqlbackup-sample
